**Creating Dummy data sets**

In [ ]:
pip install pandas  pandasai openai matplotlib scikit-learn

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: pandasai in /usr/local/lib/python3.11/dist-packages (2.0.24)
Requirement already satisfied: openai in /usr/local/lib/python3.11/dist-packages (1.61.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (3.10.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: astor<0.9.0,>=0.8.1 in /usr/local/lib/python3.11/dist-packages (from pandasai) (0.8.1)
Requirement already satisfied: duckdb<1 in /usr/local/lib/python3.11/dist-packages (from pandasai) (0.10.3)
Requirement already satisfied: faker<20.0.0,>=19.12.0 in /usr/local/lib/python3.11/dist-packages (from pandasai) (19.13.0)
Requirement already satisfied: jinja2<4.0.0,>=3.1.3 in /usr/local/lib/python3.11/dist-packages (from pandasai) (3.1.6)
Requirement already satisfied: pillow<11.0.0,>=10.1.0 in /usr/local/lib/python3.11/dist-packages (from pandasai) (10.4.0)
Requirement already satisfied: pydantic<3,>=1 in /usr/local/lib/python3.11/dist-packages (from pandasai) (2.10.6)
Requirement already satisfied: python-dotenv<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from pandasai) (1.0.1)
Requirement already satisfied: requests<3.0.0,>=2.31.0 in /usr/local/lib/python3.11/dist-packages (from pandasai) (2.32.3)
Requirement already satisfied: scipy<2.0.0,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from pandasai) (1.14.1)
Requirement already satisfied: sqlalchemy<3,>=1.4 in /usr/local/lib/python3.11/dist-packages (from pandasai) (2.0.39)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from openai) (3.7.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.11/dist-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.11/dist-packages (from openai) (4.12.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib) (3.2.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.5.0->openai) (3.10)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (2025.1.31)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.14.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2<4.0.0,>=3.1.3->pandasai) (3.0.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1->pandasai) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1->pandasai) (2.27.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.31.0->pandasai) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.31.0->pandasai) (2.3.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy<3,>=1.4->pandasai) (3.1.1)

In [ ]:
pip install numpy==1.24.4 --force-reinstall

Collecting numpy==1.24.4
  Using cached numpy-1.24.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Using cached numpy-1.24.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.4
    Uninstalling numpy-1.24.4:
      Successfully uninstalled numpy-1.24.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
treescope 0.1.9 requires numpy>=1.25.2, but you have numpy 1.24.4 which is incompatible.
blosc2 3.2.0 requires numpy>=1.26, but you have numpy 1.24.4 which is incompatible.
jax 0.5.2 requires numpy>=1.25, but you have numpy 1.24.4 which is incompatible.
tensorflow 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 1.24.4 which is incompatible.
jaxlib 0.5.1 requires numpy>=1.25, but you have numpy 1.24.4 which is incompatible.
pymc 5.21.1 requires numpy>=1.25.0, but you have numpy 1.24.4 which is incompatible.
Successfully installed numpy-1.24.4

In [ ]:
import pandas as pd
import numpy as np
from random import choices

In [ ]:
np.random.seed(10)

In [ ]:
num_records = 1000
num_outlets = 10
num_products = 5

In [ ]:
#quaters 2 (Jan-March)(apr-jun)
dates = pd.date_range(start = '2023-01-01', end= '2023-06-30')
dates = choices(dates, k=num_records)

In [ ]:
len(dates)

1000

In [ ]:
dates

[Timestamp('2023-01-31 00:00:00'),
 Timestamp('2023-06-12 00:00:00'),
 Timestamp('2023-03-04 00:00:00'),
 Timestamp('2023-05-17 00:00:00'),
 Timestamp('2023-01-18 00:00:00'),
 Timestamp('2023-03-08 00:00:00'),
 Timestamp('2023-06-29 00:00:00'),
 Timestamp('2023-03-12 00:00:00'),
 Timestamp('2023-04-12 00:00:00'),
 Timestamp('2023-03-20 00:00:00'),
 Timestamp('2023-05-04 00:00:00'),
 Timestamp('2023-06-20 00:00:00'),
 Timestamp('2023-03-02 00:00:00'),
 Timestamp('2023-03-07 00:00:00'),
 Timestamp('2023-01-13 00:00:00'),
 Timestamp('2023-03-19 00:00:00'),
 Timestamp('2023-06-30 00:00:00'),
 Timestamp('2023-06-20 00:00:00'),
 Timestamp('2023-04-06 00:00:00'),
 Timestamp('2023-01-05 00:00:00'),
 Timestamp('2023-02-17 00:00:00'),
 Timestamp('2023-05-25 00:00:00'),
 Timestamp('2023-04-01 00:00:00'),
 Timestamp('2023-01-23 00:00:00'),
 Timestamp('2023-03-31 00:00:00'),
 Timestamp('2023-04-07 00:00:00'),
 Timestamp('2023-04-03 00:00:00'),
 Timestamp('2023-03-30 00:00:00'),
 Timestamp('2023-05-05 00:00:00'),
 Timestamp('2023-04-24 00:00:00'),
 Timestamp('2023-05-31 00:00:00'),
 Timestamp('2023-04-07 00:00:00'),
 Timestamp('2023-05-28 00:00:00'),
 Timestamp('2023-04-13 00:00:00'),
 Timestamp('2023-06-10 00:00:00'),
 Timestamp('2023-05-11 00:00:00'),
 Timestamp('2023-01-21 00:00:00'),
 Timestamp('2023-05-18 00:00:00'),
 Timestamp('2023-01-12 00:00:00'),
 Timestamp('2023-03-28 00:00:00'),
 Timestamp('2023-05-17 00:00:00'),
 Timestamp('2023-02-10 00:00:00'),
 Timestamp('2023-01-04 00:00:00'),
 Timestamp('2023-02-26 00:00:00'),
 Timestamp('2023-06-02 00:00:00'),
 Timestamp('2023-02-25 00:00:00'),
 Timestamp('2023-05-03 00:00:00'),
 Timestamp('2023-02-11 00:00:00'),
 Timestamp('2023-03-27 00:00:00'),
 Timestamp('2023-01-28 00:00:00'),
 Timestamp('2023-06-25 00:00:00'),
 Timestamp('2023-03-21 00:00:00'),
 Timestamp('2023-06-10 00:00:00'),
 Timestamp('2023-05-28 00:00:00'),
 Timestamp('2023-05-27 00:00:00'),
 Timestamp('2023-01-27 00:00:00'),
 Timestamp('2023-01-10 00:00:00'),
 Timestamp('2023-03-19 00:00:00'),
 Timestamp('2023-02-27 00:00:00'),
 Timestamp('2023-02-01 00:00:00'),
 Timestamp('2023-05-15 00:00:00'),
 Timestamp('2023-02-21 00:00:00'),
 Timestamp('2023-01-18 00:00:00'),
 Timestamp('2023-05-18 00:00:00'),
 Timestamp('2023-05-12 00:00:00'),
 Timestamp('2023-01-01 00:00:00'),
 Timestamp('2023-02-18 00:00:00'),
 Timestamp('2023-04-05 00:00:00'),
 Timestamp('2023-01-04 00:00:00'),
 Timestamp('2023-03-03 00:00:00'),
 Timestamp('2023-05-03 00:00:00'),
 Timestamp('2023-03-09 00:00:00'),
 Timestamp('2023-01-08 00:00:00'),
 Timestamp('2023-01-03 00:00:00'),
 Timestamp('2023-04-14 00:00:00'),
 Timestamp('2023-01-17 00:00:00'),
 Timestamp('2023-06-06 00:00:00'),
 Timestamp('2023-01-28 00:00:00'),
 Timestamp('2023-03-04 00:00:00'),
 Timestamp('2023-01-18 00:00:00'),
 Timestamp('2023-04-13 00:00:00'),
 Timestamp('2023-06-24 00:00:00'),
 Timestamp('2023-06-24 00:00:00'),
 Timestamp('2023-04-14 00:00:00'),
 Timestamp('2023-02-26 00:00:00'),
 Timestamp('2023-03-24 00:00:00'),
 Timestamp('2023-04-28 00:00:00'),
 Timestamp('2023-04-10 00:00:00'),
 Timestamp('2023-03-30 00:00:00'),
 Timestamp('2023-05-06 00:00:00'),
 Timestamp('2023-02-07 00:00:00'),
 Timestamp('2023-05-28 00:00:00'),
 Timestamp('2023-01-12 00:00:00'),
 Timestamp('2023-01-04 00:00:00'),
 Timestamp('2023-04-26 00:00:00'),
 Timestamp('2023-06-26 00:00:00'),
 Timestamp('2023-06-11 00:00:00'),
 Timestamp('2023-03-10 00:00:00'),
 Timestamp('2023-04-29 00:00:00'),
 Timestamp('2023-02-15 00:00:00'),
 Timestamp('2023-02-09 00:00:00'),
 Timestamp('2023-02-18 00:00:00'),
 Timestamp('2023-06-15 00:00:00'),
 Timestamp('2023-03-20 00:00:00'),
 Timestamp('2023-05-05 00:00:00'),
 Timestamp('2023-03-24 00:00:00'),
 Timestamp('2023-06-29 00:00:00'),
 Timestamp('2023-06-18 00:00:00'),
 Timestamp('2023-06-11 00:00:00'),
 Timestamp('2023-01-17 00:00:00'),
 Timestamp('2023-04-21 00:00:00'),
 Timestamp('2023-05-22 00:00:00'),
 Timestamp('2023-02-18 00:00:00'),
 Timestamp('2023-04-14 00:00:00'),
 Timestamp('2023-03-25 00:00:00'),
 Timestamp('2023-02-24 00:00:00'),
 Timestamp('2023-02-09 00:00:00'),
 Timestamp('2023-02-01 00:00:00'),
 Timestamp('2023-04-18 00:00:00'),
 Timestamp('2023-03-17 00:00:00'),
 Timestamp('2023-03-19 00:00:00'),
 Timestamp('2023-02-03 00:00:00'),
 Timestamp('2023-06-21 00:00:00'),
 Timestamp('2023-01-29 00:00:00'),
 Timestamp('2023-04-30 00:00:00'),
 Timestamp('2023-04-06 00:00:00'),
 Timestamp('2023-03-26 00:00:00'),
 Timestamp('2023-06-05 00:00:00'),
 Timestamp('2023-01-09 00:00:00'),
 Timestamp('2023-02-04 00:00:00'),
 Timestamp('2023-01-31 00:00:00'),
 Timestamp('2023-04-11 00:00:00'),
 Timestamp('2023-02-26 00:00:00'),
 Timestamp('2023-05-07 00:00:00'),
 Timestamp('2023-05-04 00:00:00'),
 Timestamp('2023-03-09 00:00:00'),
 Timestamp('2023-05-02 00:00:00'),
 Timestamp('2023-05-12 00:00:00'),
 Timestamp('2023-02-08 00:00:00'),
 Timestamp('2023-02-09 00:00:00'),
 Timestamp('2023-03-06 00:00:00'),
 Timestamp('2023-03-05 00:00:00'),
 Timestamp('2023-05-29 00:00:00'),
 Timestamp('2023-01-02 00:00:00'),
 Timestamp('2023-01-09 00:00:00'),
 Timestamp('2023-03-03 00:00:00'),
 Timestamp('2023-03-03 00:00:00'),
 Timestamp('2023-04-04 00:00:00'),
 Timestamp('2023-06-01 00:00:00'),
 Timestamp('2023-02-24 00:00:00'),
 Timestamp('2023-01-18 00:00:00'),
 Timestamp('2023-01-01 00:00:00'),
 Timestamp('2023-02-17 00:00:00'),
 Timestamp('2023-05-24 00:00:00'),
 Timestamp('2023-06-04 00:00:00'),
 Timestamp('2023-05-19 00:00:00'),
 Timestamp('2023-06-23 00:00:00'),
 Timestamp('2023-03-24 00:00:00'),
 Timestamp('2023-04-15 00:00:00'),
 Timestamp('2023-04-12 00:00:00'),
 Timestamp('2023-06-08 00:00:00'),
 Timestamp('2023-03-23 00:00:00'),
 Timestamp('2023-03-30 00:00:00'),
 Timestamp('2023-05-30 00:00:00'),
 Timestamp('2023-04-14 00:00:00'),
 Timestamp('2023-05-31 00:00:00'),
 Timestamp('2023-03-08 00:00:00'),
 Timestamp('2023-01-15 00:00:00'),
 Timestamp('2023-03-03 00:00:00'),
 Timestamp('2023-03-17 00:00:00'),
 Timestamp('2023-04-26 00:00:00'),
 Timestamp('2023-05-06 00:00:00'),
 Timestamp('2023-04-07 00:00:00'),
 Timestamp('2023-06-08 00:00:00'),
 Timestamp('2023-05-04 00:00:00'),
 Timestamp('2023-03-09 00:00:00'),
 Timestamp('2023-06-27 00:00:00'),
 Timestamp('2023-01-31 00:00:00'),
 Timestamp('2023-04-10 00:00:00'),
 Timestamp('2023-04-19 00:00:00'),
 Timestamp('2023-04-26 00:00:00'),
 Timestamp('2023-02-06 00:00:00'),
 Timestamp('2023-03-03 00:00:00'),
 Timestamp('2023-05-11 00:00:00'),
 Timestamp('2023-01-11 00:00:00'),
 Timestamp('2023-01-20 00:00:00'),
 Timestamp('2023-05-20 00:00:00'),
 Timestamp('2023-01-10 00:00:00'),
 Timestamp('2023-04-14 00:00:00'),
 Timestamp('2023-02-17 00:00:00'),
 Timestamp('2023-03-17 00:00:00'),
 Timestamp('2023-05-19 00:00:00'),
 Timestamp('2023-02-04 00:00:00'),
 Timestamp('2023-03-15 00:00:00'),
 Timestamp('2023-02-05 00:00:00'),
 Timestamp('2023-04-12 00:00:00'),
 Timestamp('2023-05-27 00:00:00'),
 Timestamp('2023-06-17 00:00:00'),
 Timestamp('2023-04-30 00:00:00'),
 Timestamp('2023-02-27 00:00:00'),
 Timestamp('2023-05-02 00:00:00'),
 Timestamp('2023-02-09 00:00:00'),
 Timestamp('2023-06-23 00:00:00'),
 Timestamp('2023-05-04 00:00:00'),
 Timestamp('2023-05-18 00:00:00'),
 Timestamp('2023-05-05 00:00:00'),
 Timestamp('2023-03-28 00:00:00'),
 Timestamp('2023-04-01 00:00:00'),
 Timestamp('2023-05-04 00:00:00'),
 Timestamp('2023-01-12 00:00:00'),
 Timestamp('2023-02-12 00:00:00'),
 Timestamp('2023-03-30 00:00:00'),
 Timestamp('2023-06-26 00:00:00'),
 Timestamp('2023-02-12 00:00:00'),
 Timestamp('2023-06-24 00:00:00'),
 Timestamp('2023-05-28 00:00:00'),
 Timestamp('2023-03-29 00:00:00'),
 Timestamp('2023-01-14 00:00:00'),
 Timestamp('2023-05-08 00:00:00'),
 Timestamp('2023-03-06 00:00:00'),
 Timestamp('2023-06-01 00:00:00'),
 Timestamp('2023-04-17 00:00:00'),
 Timestamp('2023-06-18 00:00:00'),
 Timestamp('2023-03-30 00:00:00'),
 Timestamp('2023-06-03 00:00:00'),
 Timestamp('2023-02-27 00:00:00'),
 Timestamp('2023-06-29 00:00:00'),
 Timestamp('2023-04-22 00:00:00'),
 Timestamp('2023-04-01 00:00:00'),
 Timestamp('2023-01-15 00:00:00'),
 Timestamp('2023-01-14 00:00:00'),
 Timestamp('2023-02-24 00:00:00'),
 Timestamp('2023-05-23 00:00:00'),
 Timestamp('2023-04-06 00:00:00'),
 Timestamp('2023-01-21 00:00:00'),
 Timestamp('2023-02-18 00:00:00'),
 Timestamp('2023-04-16 00:00:00'),
 Timestamp('2023-02-22 00:00:00'),
 Timestamp('2023-04-13 00:00:00'),
 Timestamp('2023-06-29 00:00:00'),
 Timestamp('2023-06-22 00:00:00'),
 Timestamp('2023-02-16 00:00:00'),
 Timestamp('2023-04-20 00:00:00'),
 Timestamp('2023-03-23 00:00:00'),
 Timestamp('2023-01-22 00:00:00'),
 Timestamp('2023-06-05 00:00:00'),
 Timestamp('2023-04-02 00:00:00'),
 Timestamp('2023-04-28 00:00:00'),
 Timestamp('2023-01-07 00:00:00'),
 Timestamp('2023-04-12 00:00:00'),
 Timestamp('2023-04-11 00:00:00'),
 Timestamp('2023-01-26 00:00:00'),
 Timestamp('2023-06-02 00:00:00'),
 Timestamp('2023-01-14 00:00:00'),
 Timestamp('2023-04-06 00:00:00'),
 Timestamp('2023-04-26 00:00:00'),
 Timestamp('2023-05-24 00:00:00'),
 Timestamp('2023-02-09 00:00:00'),
 Timestamp('2023-05-29 00:00:00'),
 Timestamp('2023-02-15 00:00:00'),
 Timestamp('2023-03-24 00:00:00'),
 Timestamp('2023-04-14 00:00:00'),
 Timestamp('2023-05-30 00:00:00'),
 Timestamp('2023-02-18 00:00:00'),
 Timestamp('2023-03-30 00:00:00'),
 Timestamp('2023-02-14 00:00:00'),
 Timestamp('2023-05-16 00:00:00'),
 Timestamp('2023-04-14 00:00:00'),
 Timestamp('2023-05-05 00:00:00'),
 Timestamp('2023-03-21 00:00:00'),
 Timestamp('2023-02-13 00:00:00'),
 Timestamp('2023-02-15 00:00:00'),
 Timestamp('2023-01-13 00:00:00'),
 Timestamp('2023-02-16 00:00:00'),
 Timestamp('2023-06-19 00:00:00'),
 Timestamp('2023-06-30 00:00:00'),
 Timestamp('2023-01-14 00:00:00'),
 Timestamp('2023-02-06 00:00:00'),
 Timestamp('2023-05-23 00:00:00'),
 Timestamp('2023-01-24 00:00:00'),
 Timestamp('2023-05-21 00:00:00'),
 Timestamp('2023-04-27 00:00:00'),
 Timestamp('2023-03-03 00:00:00'),
 Timestamp('2023-02-04 00:00:00'),
 Timestamp('2023-04-20 00:00:00'),
 Timestamp('2023-02-14 00:00:00'),
 Timestamp('2023-03-14 00:00:00'),
 Timestamp('2023-04-29 00:00:00'),
 Timestamp('2023-02-02 00:00:00'),
 Timestamp('2023-03-21 00:00:00'),
 Timestamp('2023-01-25 00:00:00'),
 Timestamp('2023-01-29 00:00:00'),
 Timestamp('2023-04-07 00:00:00'),
 Timestamp('2023-06-06 00:00:00'),
 Timestamp('2023-05-21 00:00:00'),
 Timestamp('2023-05-01 00:00:00'),
 Timestamp('2023-01-08 00:00:00'),
 Timestamp('2023-03-18 00:00:00'),
 Timestamp('2023-03-21 00:00:00'),
 Timestamp('2023-02-12 00:00:00'),
 Timestamp('2023-06-07 00:00:00'),
 Timestamp('2023-01-08 00:00:00'),
 Timestamp('2023-06-12 00:00:00'),
 Timestamp('2023-02-27 00:00:00'),
 Timestamp('2023-02-16 00:00:00'),
 Timestamp('2023-03-21 00:00:00'),
 Timestamp('2023-06-04 00:00:00'),
 Timestamp('2023-06-18 00:00:00'),
 Timestamp('2023-04-01 00:00:00'),
 Timestamp('2023-05-07 00:00:00'),
 Timestamp('2023-04-15 00:00:00'),
 Timestamp('2023-05-08 00:00:00'),
 Timestamp('2023-01-12 00:00:00'),
 Timestamp('2023-01-30 00:00:00'),
 Timestamp('2023-02-05 00:00:00'),
 Timestamp('2023-01-20 00:00:00'),
 Timestamp('2023-06-01 00:00:00'),
 Timestamp('2023-01-23 00:00:00'),
 Timestamp('2023-01-31 00:00:00'),
 Timestamp('2023-04-07 00:00:00'),
 Timestamp('2023-02-02 00:00:00'),
 Timestamp('2023-06-25 00:00:00'),
 Timestamp('2023-01-19 00:00:00'),
 Timestamp('2023-06-23 00:00:00'),
 Timestamp('2023-03-10 00:00:00'),
 Timestamp('2023-06-23 00:00:00'),
 Timestamp('2023-04-20 00:00:00'),
 Timestamp('2023-03-06 00:00:00'),
 Timestamp('2023-04-10 00:00:00'),
 Timestamp('2023-05-25 00:00:00'),
 Timestamp('2023-05-08 00:00:00'),
 Timestamp('2023-05-21 00:00:00'),
 Timestamp('2023-03-28 00:00:00'),
 Timestamp('2023-05-10 00:00:00'),
 Timestamp('2023-04-04 00:00:00'),
 Timestamp('2023-01-25 00:00:00'),
 Timestamp('2023-05-08 00:00:00'),
 Timestamp('2023-01-30 00:00:00'),
 Timestamp('2023-03-31 00:00:00'),
 Timestamp('2023-03-13 00:00:00'),
 Timestamp('2023-03-02 00:00:00'),
 Timestamp('2023-06-09 00:00:00'),
 Timestamp('2023-04-27 00:00:00'),
 Timestamp('2023-01-18 00:00:00'),
 Timestamp('2023-06-05 00:00:00'),
 Timestamp('2023-06-21 00:00:00'),
 Timestamp('2023-01-08 00:00:00'),
 Timestamp('2023-04-06 00:00:00'),
 Timestamp('2023-05-09 00:00:00'),
 Timestamp('2023-05-02 00:00:00'),
 Timestamp('2023-04-26 00:00:00'),
 Timestamp('2023-04-08 00:00:00'),
 Timestamp('2023-06-30 00:00:00'),
 Timestamp('2023-04-16 00:00:00'),
 Timestamp('2023-05-13 00:00:00'),
 Timestamp('2023-06-24 00:00:00'),
 Timestamp('2023-02-14 00:00:00'),
 Timestamp('2023-06-24 00:00:00'),
 Timestamp('2023-06-23 00:00:00'),
 Timestamp('2023-02-23 00:00:00'),
 Timestamp('2023-06-20 00:00:00'),
 Timestamp('2023-06-10 00:00:00'),
 Timestamp('2023-05-19 00:00:00'),
 Timestamp('2023-06-03 00:00:00'),
 Timestamp('2023-02-19 00:00:00'),
 Timestamp('2023-04-20 00:00:00'),
 Timestamp('2023-01-06 00:00:00'),
 Timestamp('2023-03-07 00:00:00'),
 Timestamp('2023-06-11 00:00:00'),
 Timestamp('2023-03-18 00:00:00'),
 Timestamp('2023-01-05 00:00:00'),
 Timestamp('2023-01-05 00:00:00'),
 Timestamp('2023-02-23 00:00:00'),
 Timestamp('2023-03-20 00:00:00'),
 Timestamp('2023-01-22 00:00:00'),
 Timestamp('2023-03-01 00:00:00'),
 Timestamp('2023-04-29 00:00:00'),
 Timestamp('2023-01-04 00:00:00'),
 Timestamp('2023-05-13 00:00:00'),
 Timestamp('2023-05-21 00:00:00'),
 Timestamp('2023-01-03 00:00:00'),
 Timestamp('2023-01-15 00:00:00'),
 Timestamp('2023-06-24 00:00:00'),
 Timestamp('2023-06-06 00:00:00'),
 Timestamp('2023-05-20 00:00:00'),
 Timestamp('2023-01-19 00:00:00'),
 Timestamp('2023-02-01 00:00:00'),
 Timestamp('2023-04-12 00:00:00'),
 Timestamp('2023-05-24 00:00:00'),
 Timestamp('2023-02-19 00:00:00'),
 Timestamp('2023-01-17 00:00:00'),
 Timestamp('2023-06-04 00:00:00'),
 Timestamp('2023-01-26 00:00:00'),
 Timestamp('2023-02-21 00:00:00'),
 Timestamp('2023-02-26 00:00:00'),
 Timestamp('2023-01-24 00:00:00'),
 Timestamp('2023-01-06 00:00:00'),
 Timestamp('2023-04-12 00:00:00'),
 Timestamp('2023-03-26 00:00:00'),
 Timestamp('2023-01-09 00:00:00'),
 Timestamp('2023-01-13 00:00:00'),
 Timestamp('2023-03-14 00:00:00'),
 Timestamp('2023-03-21 00:00:00'),
 Timestamp('2023-06-07 00:00:00'),
 Timestamp('2023-02-04 00:00:00'),
 Timestamp('2023-02-06 00:00:00'),
 Timestamp('2023-04-04 00:00:00'),
 Timestamp('2023-05-09 00:00:00'),
 Timestamp('2023-06-09 00:00:00'),
 Timestamp('2023-06-26 00:00:00'),
 Timestamp('2023-06-02 00:00:00'),
 Timestamp('2023-03-05 00:00:00'),
 Timestamp('2023-03-13 00:00:00'),
 Timestamp('2023-04-18 00:00:00'),
 Timestamp('2023-04-30 00:00:00'),
 Timestamp('2023-03-17 00:00:00'),
 Timestamp('2023-03-16 00:00:00'),
 Timestamp('2023-03-18 00:00:00'),
 Timestamp('2023-06-20 00:00:00'),
 Timestamp('2023-02-28 00:00:00'),
 Timestamp('2023-03-31 00:00:00'),
 Timestamp('2023-04-11 00:00:00'),
 Timestamp('2023-03-31 00:00:00'),
 Timestamp('2023-01-02 00:00:00'),
 Timestamp('2023-02-16 00:00:00'),
 Timestamp('2023-03-04 00:00:00'),
 Timestamp('2023-03-08 00:00:00'),
 Timestamp('2023-02-09 00:00:00'),
 Timestamp('2023-01-31 00:00:00'),
 Timestamp('2023-03-03 00:00:00'),
 Timestamp('2023-02-08 00:00:00'),
 Timestamp('2023-02-03 00:00:00'),
 Timestamp('2023-04-29 00:00:00'),
 Timestamp('2023-04-08 00:00:00'),
 Timestamp('2023-04-28 00:00:00'),
 Timestamp('2023-06-24 00:00:00'),
 Timestamp('2023-01-04 00:00:00'),
 Timestamp('2023-06-08 00:00:00'),
 Timestamp('2023-03-16 00:00:00'),
 Timestamp('2023-06-18 00:00:00'),
 Timestamp('2023-04-19 00:00:00'),
 Timestamp('2023-01-25 00:00:00'),
 Timestamp('2023-01-08 00:00:00'),
 Timestamp('2023-01-15 00:00:00'),
 Timestamp('2023-01-30 00:00:00'),
 Timestamp('2023-05-22 00:00:00'),
 Timestamp('2023-01-22 00:00:00'),
 Timestamp('2023-04-07 00:00:00'),
 Timestamp('2023-03-03 00:00:00'),
 Timestamp('2023-05-31 00:00:00'),
 Timestamp('2023-06-01 00:00:00'),
 Timestamp('2023-03-09 00:00:00'),
 Timestamp('2023-03-05 00:00:00'),
 Timestamp('2023-02-08 00:00:00'),
 Timestamp('2023-06-29 00:00:00'),
 Timestamp('2023-02-27 00:00:00'),
 Timestamp('2023-06-05 00:00:00'),
 Timestamp('2023-02-11 00:00:00'),
 Timestamp('2023-03-23 00:00:00'),
 Timestamp('2023-06-06 00:00:00'),
 Timestamp('2023-04-08 00:00:00'),
 Timestamp('2023-03-21 00:00:00'),
 Timestamp('2023-01-06 00:00:00'),
 Timestamp('2023-03-06 00:00:00'),
 Timestamp('2023-04-29 00:00:00'),
 Timestamp('2023-05-31 00:00:00'),
 Timestamp('2023-03-02 00:00:00'),
 Timestamp('2023-02-17 00:00:00'),
 Timestamp('2023-01-27 00:00:00'),
 Timestamp('2023-03-04 00:00:00'),
 Timestamp('2023-06-21 00:00:00'),
 Timestamp('2023-03-17 00:00:00'),
 Timestamp('2023-01-26 00:00:00'),
 Timestamp('2023-01-25 00:00:00'),
 Timestamp('2023-02-14 00:00:00'),
 Timestamp('2023-04-06 00:00:00'),
 Timestamp('2023-02-23 00:00:00'),
 Timestamp('2023-01-06 00:00:00'),
 Timestamp('2023-03-17 00:00:00'),
 Timestamp('2023-05-12 00:00:00'),
 Timestamp('2023-02-19 00:00:00'),
 Timestamp('2023-03-20 00:00:00'),
 Timestamp('2023-05-20 00:00:00'),
 Timestamp('2023-04-20 00:00:00'),
 Timestamp('2023-05-29 00:00:00'),
 Timestamp('2023-01-09 00:00:00'),
 Timestamp('2023-03-06 00:00:00'),
 Timestamp('2023-02-07 00:00:00'),
 Timestamp('2023-04-24 00:00:00'),
 Timestamp('2023-01-05 00:00:00'),
 Timestamp('2023-04-13 00:00:00'),
 Timestamp('2023-02-28 00:00:00'),
 Timestamp('2023-01-05 00:00:00'),
 Timestamp('2023-02-15 00:00:00'),
 Timestamp('2023-02-21 00:00:00'),
 Timestamp('2023-02-09 00:00:00'),
 Timestamp('2023-03-15 00:00:00'),
 Timestamp('2023-02-15 00:00:00'),
 Timestamp('2023-04-18 00:00:00'),
 Timestamp('2023-04-03 00:00:00'),
 Timestamp('2023-02-20 00:00:00'),
 Timestamp('2023-06-14 00:00:00'),
 Timestamp('2023-02-01 00:00:00'),
 Timestamp('2023-03-24 00:00:00'),
 Timestamp('2023-02-09 00:00:00'),
 Timestamp('2023-04-03 00:00:00'),
 Timestamp('2023-06-03 00:00:00'),
 Timestamp('2023-05-14 00:00:00'),
 Timestamp('2023-05-16 00:00:00'),
 Timestamp('2023-05-08 00:00:00'),
 Timestamp('2023-06-27 00:00:00'),
 Timestamp('2023-05-08 00:00:00'),
 Timestamp('2023-03-08 00:00:00'),
 Timestamp('2023-04-29 00:00:00'),
 Timestamp('2023-06-05 00:00:00'),
 Timestamp('2023-03-26 00:00:00'),
 Timestamp('2023-02-23 00:00:00'),
 Timestamp('2023-06-08 00:00:00'),
 Timestamp('2023-05-27 00:00:00'),
 Timestamp('2023-01-28 00:00:00'),
 Timestamp('2023-05-01 00:00:00'),
 Timestamp('2023-05-12 00:00:00'),
 Timestamp('2023-01-09 00:00:00'),
 Timestamp('2023-04-09 00:00:00'),
 Timestamp('2023-05-17 00:00:00'),
 Timestamp('2023-01-21 00:00:00'),
 Timestamp('2023-02-14 00:00:00'),
 Timestamp('2023-06-22 00:00:00'),
 Timestamp('2023-04-01 00:00:00'),
 Timestamp('2023-06-23 00:00:00'),
 Timestamp('2023-03-17 00:00:00'),
 Timestamp('2023-04-05 00:00:00'),
 Timestamp('2023-02-05 00:00:00'),
 Timestamp('2023-01-10 00:00:00'),
 Timestamp('2023-05-17 00:00:00'),
 Timestamp('2023-05-23 00:00:00'),
 Timestamp('2023-05-10 00:00:00'),
 Timestamp('2023-03-24 00:00:00'),
 Timestamp('2023-06-13 00:00:00'),
 Timestamp('2023-05-25 00:00:00'),
 Timestamp('2023-05-05 00:00:00'),
 Timestamp('2023-06-26 00:00:00'),
 Timestamp('2023-02-20 00:00:00'),
 Timestamp('2023-05-23 00:00:00'),
 Timestamp('2023-03-07 00:00:00'),
 Timestamp('2023-02-14 00:00:00'),
 Timestamp('2023-02-13 00:00:00'),
 Timestamp('2023-01-24 00:00:00'),
 Timestamp('2023-06-28 00:00:00'),
 Timestamp('2023-06-04 00:00:00'),
 Timestamp('2023-04-28 00:00:00'),
 Timestamp('2023-02-06 00:00:00'),
 Timestamp('2023-03-08 00:00:00'),
 Timestamp('2023-04-15 00:00:00'),
 Timestamp('2023-05-19 00:00:00'),
 Timestamp('2023-01-24 00:00:00'),
 Timestamp('2023-05-14 00:00:00'),
 Timestamp('2023-05-22 00:00:00'),
 Timestamp('2023-05-23 00:00:00'),
 Timestamp('2023-03-22 00:00:00'),
 Timestamp('2023-04-09 00:00:00'),
 Timestamp('2023-06-03 00:00:00'),
 Timestamp('2023-04-04 00:00:00'),
 Timestamp('2023-02-26 00:00:00'),
 Timestamp('2023-05-24 00:00:00'),
 Timestamp('2023-05-20 00:00:00'),
 Timestamp('2023-02-02 00:00:00'),
 Timestamp('2023-06-28 00:00:00'),
 Timestamp('2023-05-27 00:00:00'),
 Timestamp('2023-06-16 00:00:00'),
 Timestamp('2023-03-14 00:00:00'),

In [ ]:
outlets = ['Outlet_'+str(i+1) for i in range(num_outlets)]
outlets = choices(outlets, k=num_records)

In [ ]:
len(outlets)

1000

In [ ]:
products = ['products_'+str(i+1) for i in range(num_products)]
products = choices(products, k=num_records)

In [ ]:
len(products)

1000

In [ ]:
units_Sold = np.random.randint(1,200, num_records)
price_per_unit = np.random.uniform(10,500, num_records)

In [ ]:
total_sales= units_Sold * price_per_unit

In [ ]:
len(total_sales)

1000

**Put this in Dataframe**

In [ ]:
df= pd.DataFrame({
    'Date': dates,
    'Outlets': outlets,
    'Products' : products,
    'Units_Solds': units_Sold,
    'Price_per_unit' : price_per_unit,
    'Total_Sales': total_sales

})

In [ ]:
OPEN_API_KEY = "you-openai-key"

In [ ]:
pip install pandasai

Requirement already satisfied: pandasai in /usr/local/lib/python3.11/dist-packages (2.0.24)
Requirement already satisfied: astor<0.9.0,>=0.8.1 in /usr/local/lib/python3.11/dist-packages (from pandasai) (0.8.1)
Requirement already satisfied: duckdb<1 in /usr/local/lib/python3.11/dist-packages (from pandasai) (0.10.3)
Requirement already satisfied: faker<20.0.0,>=19.12.0 in /usr/local/lib/python3.11/dist-packages (from pandasai) (19.13.0)
Requirement already satisfied: jinja2<4.0.0,>=3.1.3 in /usr/local/lib/python3.11/dist-packages (from pandasai) (3.1.6)
Requirement already satisfied: matplotlib<4.0.0,>=3.7.1 in /usr/local/lib/python3.11/dist-packages (from pandasai) (3.10.0)
Requirement already satisfied: openai<2 in /usr/local/lib/python3.11/dist-packages (from pandasai) (1.61.1)
Requirement already satisfied: pandas<3.0,>=2.0 in /usr/local/lib/python3.11/dist-packages (from pandasai) (2.2.2)
Requirement already satisfied: pillow<11.0.0,>=10.1.0 in /usr/local/lib/python3.11/dist-packages (from pandasai) (10.4.0)
Requirement already satisfied: pydantic<3,>=1 in /usr/local/lib/python3.11/dist-packages (from pandasai) (2.10.6)
Requirement already satisfied: python-dotenv<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from pandasai) (1.0.1)
Requirement already satisfied: requests<3.0.0,>=2.31.0 in /usr/local/lib/python3.11/dist-packages (from pandasai) (2.32.3)
Requirement already satisfied: scipy<2.0.0,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from pandasai) (1.14.1)
Requirement already satisfied: sqlalchemy<3,>=1.4 in /usr/local/lib/python3.11/dist-packages (from pandasai) (2.0.39)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.11/dist-packages (from faker<20.0.0,>=19.12.0->pandasai) (2.8.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2<4.0.0,>=3.1.3->pandasai) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (1.4.8)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (1.24.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib<4.0.0,>=3.7.1->pandasai) (3.2.1)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from openai<2->pandasai) (3.7.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai<2->pandasai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from openai<2->pandasai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai<2->pandasai) (0.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from openai<2->pandasai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.11/dist-packages (from openai<2->pandasai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.11/dist-packages (from openai<2->pandasai) (4.12.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas<3.0,>=2.0->pandasai) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<3.0,>=2.0->pandasai) (2025.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1->pandasai) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1->pandasai) (2.27.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.31.0->pandasai) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.31.0->pandasai) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.31.0->pandasai) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.31.0->pandasai) (2025.1.31)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy<3,>=1.4->pandasai) (3.1.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai<2->pandasai) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai<2->pandasai) (0.14.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.4->faker<20.0.0,>=19.12.0->pandasai) (1.17.0)

In [ ]:
#import importlib.metadata
#print(importlib.metadata.version("pandasai"))

In [ ]:
from pandasai.llm.openai import OpenAI
from pandasai.smart_dataframe import SmartDataframe

In [ ]:
llm = OpenAI(api_token=OPEN_API_KEY)
pandas_ai = SmartDataframe(df, config={"llm": llm})

In [ ]:
df

,Date,Outlets,Products,Units_Solds,Price_per_unit,Total_Sales
0,2023-01-31,Outlet_3,products_2,10,27.204538,272.045385
1,2023-06-12,Outlet_10,products_2,126,195.408008,24621.409060
2,2023-03-04,Outlet_8,products_5,16,185.391255,2966.260076
3,2023-05-17,Outlet_2,products_4,65,137.191145,8917.424411
4,2023-01-18,Outlet_5,products_5,114,304.343828,34695.196345
...,...,...,...,...,...,...
995,2023-06-26,Outlet_4,products_2,37,19.028276,704.046201
996,2023-03-13,Outlet_5,products_5,91,372.000914,33852.083211
997,2023-03-21,Outlet_6,products_3,148,37.062541,5485.256005
998,2023-01-02,Outlet_1,products_2,33,289.563788,9555.605018
999,2023-03-28,Outlet_2,products_3,31,393.705338,12204.865493

In [ ]:
response = pandas_ai.chat("Round price_per_unit and Total_sales to 2 decimal places.")
print(response)

ERROR:pandasai.helpers.logger:Pipeline failed on step 3: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Unfortunately, I was not able to answer your question, because of the following error:

Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/pandasai/pipelines/chat/generate_chat_pipeline.py", line 283, in run
    output = (self.code_generation_pipeline | self.code_execution_pipeline).run(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pandasai/pipelines/pipeline.py", line 137, in run
    raise e
  File "/usr/local/lib/python3.11/dist-packages/pandasai/pipelines/pipeline.py", line 101, in run
    step_output = logic.execute(
                  ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pandasai/pipelines/chat/code_generator.py", line 33, in execute
    code = pipeline_context.config.llm.generate_code(input, pipeline_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pandasai/llm/base.py", line 196, in generate_code
    response = self.call(instruction, context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pandasai/llm/base.py", line 385, in call
    self.chat_completion(self.last_prompt, memory)
  File "/usr/local/lib/python3.11/dist-packages/pandasai/llm/base.py", line 359, in chat_completion
    response = self.client.create(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/resources/chat/completions.py", line 863, in create
    return self._post(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 1283, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 960, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 1049, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 1098, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 1049, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 1098, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 1064, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

In [ ]:
response = pandas_ai.chat("Round price_per_unit and Total_sales to 2 decimal places.")
print(response)

ERROR:pandasai.helpers.logger:Pipeline failed on step 3: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Unfortunately, I was not able to answer your question, because of the following error:

Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/pandasai/pipelines/chat/generate_chat_pipeline.py", line 283, in run
    output = (self.code_generation_pipeline | self.code_execution_pipeline).run(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pandasai/pipelines/pipeline.py", line 137, in run
    raise e
  File "/usr/local/lib/python3.11/dist-packages/pandasai/pipelines/pipeline.py", line 101, in run
    step_output = logic.execute(
                  ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pandasai/pipelines/chat/code_generator.py", line 33, in execute
    code = pipeline_context.config.llm.generate_code(input, pipeline_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pandasai/llm/base.py", line 196, in generate_code
    response = self.call(instruction, context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pandasai/llm/base.py", line 385, in call
    self.chat_completion(self.last_prompt, memory)
  File "/usr/local/lib/python3.11/dist-packages/pandasai/llm/base.py", line 359, in chat_completion
    response = self.client.create(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_utils/_utils.py", line 279, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/resources/chat/completions.py", line 863, in create
    return self._post(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 1283, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 960, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 1049, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 1098, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 1049, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 1098, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/openai/_base_client.py", line 1064, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

In [ ]:
df

**Charting**

In [ ]:
response = pandas_ai.chat("Which product is most profitable?")
print(response)

In [ ]:
response = pandas_ai.chat("Plot the bar chart of the product based on total_sales by arranign product ascending")
print(response)

In [ ]:
response = pandas_ai.chat("can you name product_1 as apple?")
print(response)